---
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Simple

Resources:
  Func1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/func1
      Handler: index.handler
      Runtime: python2.7
  Func2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/func2
      Handler: index.handler
      Runtime: python2.7

Outputs:
  Func1Arn:
    Value: !GetAtt Func1.Arn
  Func2Arn:
    Value: !GetAtt Func2.Arn
